apiVersion: v1
kind: ServiceMonitor
metadata:
  name: ai-math-tutor-metrics
  namespace: ai-math-tutor
  labels:
    app: ai-math-tutor
spec:
  selector:
    matchLabels:
      app: math-engine
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: api-gateway-metrics
  namespace: ai-math-tutor
  labels:
    app: ai-math-tutor
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ai-math-tutor-alerts
  namespace: ai-math-tutor
  labels:
    app: ai-math-tutor
spec:
  groups:
  - name: ai-math-tutor.rules
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Error rate is above 10% for 5 minutes"
    
    - alert: HighResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High response time detected"
        description: "95th percentile response time is above 1 second"
    
    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ $labels.pod }} is restarting frequently"
    
    - alert: HighMemoryUsage
      expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage"
        description: "Container memory usage is above 90%"
    
    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total[5m]) / container_spec_cpu_quota * 100 > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage"
        description: "Container CPU usage is above 80%"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operated
  namespace: ai-math-tutor
  labels:
    operated-prometheus: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus